---
- hosts: localhost
  become: no
  connection: local
  pre_tasks:
  # TODO: yum repos
  # TODO: repo GPG keys
  - name: Install required packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
    - SpiderOakBlue
    - redhat-internal-cert-install
    - redhat-internal-NetworkManager-openvpn-profiles
    - libselinux-python
    - terminator
    - python3-tox
    - libffi
    - libffi-devel
    - openssl-devel
    - redhat-rpm-config
    - python-devel
    - python3-devel
    become: yes
  roles:
  - scm
  - zsh
  - neovim
  - docker
  post_tasks:
  - name: Change shell to zsh
    user:
      name: jdetiber
      shell: /usr/bin/zsh
      state: present
