---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - zsh

- name: .zshrc
  copy:
    src: .zshrc
    dest: /home/jdetiber/.zshrc
    owner: jdetiber
    group: jdetiber
    mode: 0660

