---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - zsh
  become: yes

- name: .zshrc
  copy:
    src: .zshrc
    dest: /home/jdetiber/.zshrc
    owner: jdetiber
    group: jdetiber
    mode: 0660

- name: zplug
  unarchive:
    src: zplug.tgz
    dest: /home/jdetiber/
    creates: /home/jdetiber/.zplug
    owner: jdetiber
    group: jdetiber
