---
repo_root: /home/jdetiber/git
github_repo_root: "{{ repo_root }}/github"

github_repos:
- name:  ansible
  subdir: ansible
  remotes:
  - name: upstream
    org: ansible
  branches:
  - name: stable-2.2
    remote: upstream
  - name: devel
    remote: upstream
- name: moto
  subdir: ansible
  remotes:
  - name: upstream
    org: spulec
  branches: []
- name: molecule
  subdir: ansible
  remotes:
  - name: upstream
    org: metacloud
  branches:
  - name: v2
    remote: upstream
  - name: master
    remote: upstream
- name: python-openshift
  subdir: ftl-toolbox
  remotes:
  - name: upstream
    org: ftl-toolbox
  branches: []
- name: kubernetes
  subdir: k8s
  remotes:
  - name: upstream
    org: kubernetes
  branches: []
- name: client-python
  subdir: k8s
  remotes:
  - name: upstream
    org: kubernetes-incubator
  branches: []
- name: kargo
  subdir: k8s
  remotes:
  - name: upstream
    org: kubernetes-incubator
  branches: []
- name: ansible_fest_2016
  subdir: conference_talks
  remotes: []
  branches: []
#- name: demo-ansible
#  subdir: keynote_demos/2015
#  remotes:
#  - name: upstream
#    org: 2015-Middleware-Keynote
#  branches: []
#- name: hexboard
#  subdir: keynote_demos/2015
#  remotes:
#  - name: upstream
#    org: 2015-Middleware-Keynote
#  branches: []
#- name: demo-env-ansible
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: cicd
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: cicd-templates
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: mobile-app
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: openshift-jenkins-s2i-config
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: score-server
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: templates
#  subdir: keynote_demos/2016
#  remotes:
#  - name: upstream
#    org: Red-Hat-Middleware-Keynote
#  branches: []
#- name: che-proxy
#  origin: Red-Hat-Middleware-Keynote
#  subdir: keynote_demos/2016
#  remotes: []
#  branches: []
#- name: game-mechanics-server
#  origin: Red-Hat-Middleware-Keynote
#  subdir: keynote_demos/2016
#  remotes: []
#  branches: []
#- name: nginx-proxy
#  origin: Red-Hat-Middleware-Keynote
#  subdir: keynote_demos/2016
#  remotes: []
#  branches: []
#- name: s2i-nginx
#  subdir: keynote_demos/2016
#  remotes: []
#  branches: []
#- name: s2i-nginx-nodejs
#  subdir: keynote_demos/2016
#  remotes: []
#  branches: []
- name: aos-ansible
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: openshift-ansible
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: openshift-ansible-contrib
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: openshift-docs
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: origin
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: ose
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: online
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: openshift-tools
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
- name: openshift-ansible-ops
  subdir: openshift
  remotes:
  - name: upstream
    org: openshift
  branches: []
