---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - neovim
  become: yes

- name: Neovim Config
  unarchive:
    src: nvim.tgz
    dest: /home/jdetiber/.config
    creates: /home/jdetiber/.config/nvim
    owner: jdetiber
    group: jdetiber
